relative-paths: true
models:
      - model.npz
vocabs:
      - vocab.slen.spm
      - vocab.slen.spm
beam-size: 6
normalize: 1.0
word-penalty: 0
mini-batch: 32
maxi-batch: 100
maxi-batch-sort: src
workspace: 4000
max-length-factor: 2.0
