relative-paths: true
models:
      - model.npz
vocabs:
      - vocab.uken.spm
      - vocab.uken.spm
shortlist:
    - lex.s2t.bin
    - false
beam-size: 1
normalize: 1.0
word-penalty: 0
mini-batch: 64
maxi-batch: 100
maxi-batch-sort: src
workspace: 4000
max-length-factor: 2.0
skip-cost: true
