relative-paths: true
models:
  - model.npz
vocabs:
  - vocab.hbseng.spm
  - vocab.hbseng.spm
beam-size: 1
normalize: 1
word-penalty: 0
mini-batch: 32
maxi-batch: 100
maxi-batch-sort: src
workspace: 6000
